name: Backup Repo

on:
  schedule:
    - cron: "*/5 * * * *" # Runs every 5 minutes
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
    - name: Clone the repository
      uses: actions/checkout@v3

    - name: Compress the repository
      run: tar -czf repo-backup.tar.gz .

    - name: Upload to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        BUCKET_NAME: "juliansbucketforbackend"
      run: |
        aws s3 cp repo-backup.tar.gz s3://$BUCKET_NAME/repo-backup-$(date +'%Y-%m-%d').tar.gz
