name: Upload Image to Registry

on:
  push:
    branches: [ "development", "main"]

permissions:
  contents: read
  packages: write

jobs:
  buildImage:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set Image Name
        run: echo "IMAGE_NAME=ghcr.io/${{ github.actor }}/ds-translator_backend" >> $GITHUB_ENV

      - name: Build Docker Image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME:latest

      - name: Push Image to GHCR
        run: docker push $IMAGE_NAME:latest


